name: GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: mkdocs gh-deploy --strict --force
