name: Go docs

on:
  push:
    branches:
      - main

jobs:
  go-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Refresh pkg.go.dev docs
        run: |
          go mod init foo
          go get github.com/boyvinall/observability-demo/...@main
