name: main

on:
  push:
    branches:
      - main

jobs:

  go-docs:
    runs-on: ubuntu-22.04
    steps:
      - run: touch go.sum
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Refresh pkg.go.dev docs
        run: |
          go mod init foo
          go get github.com/boyvinall/observability-demo/...@main

  trigger-github-pages:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy
        run: mkdocs gh-deploy --strict --force
